import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#3c0091",
        "surface-container-highest": "#353436",
        "tertiary": "#ffffff",
        "inverse-surface": "#e5e2e3",
        "tertiary-fixed": "#d8e3fb",
        "on-primary-fixed": "#161e00",
        "on-tertiary": "#263143",
        "on-surface": "#e5e2e3",
        "error-container": "#93000a",
        "primary-fixed-dim": "#abd600",
        "on-tertiary-fixed": "#111c2d",
        "on-background": "#e5e2e3",
        "on-surface-variant": "#c4c9ac",
        "secondary": "#d0bcff",
        "inverse-primary": "#506600",
        "secondary-fixed": "#e9ddff",
        "on-primary": "#283500",
        "surface-variant": "#353436",
        "secondary-container": "#571bc1",
        "tertiary-container": "#d8e3fb",
        "surface-bright": "#3a393a",
        "outline": "#8e9379",
        "inverse-on-surface": "#313031",
        "on-primary-container": "#556d00",
        "primary-fixed": "#c3f400",
        "on-error": "#690005",
        "background": "#131314",
        "tertiary-fixed-dim": "#bcc7de",
        "primary-container": "#c3f400",
        "surface-tint": "#abd600",
        "surface-container-low": "#1c1b1c",
        "on-error-container": "#ffdad6",
        "surface-dim": "#131314",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "outline-variant": "#444933",
        "primary": "#ffffff",
        "on-tertiary-container": "#5a6579",
        "surface-container-lowest": "#0e0e0f",
        "on-primary-fixed-variant": "#3c4d00",
        "on-tertiary-fixed-variant": "#3c475a",
        "surface-container-high": "#2a2a2b",
        "surface-container": "#201f20",
        "on-secondary-container": "#c4abff",
        "surface": "#131314",
        "on-secondary-fixed-variant": "#5516be",
      },
      fontFamily: {
        "headline": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "body": ["var(--font-inter)", "Inter", "sans-serif"],
        "label": ["var(--font-inter)", "Inter", "sans-serif"],
        "mono": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
